### ISSUE TITLE
could not run on simulator or iphone

### ISSUE THREAD

**Issue by litt1e-p** [ivanmoskalev/IMOFilterStack#1]
I have pod install them, it can build successfully but run on simulator or iphone

**Comment by ivanmoskalev** [comment]
Hello. What exactly happens?

**Comment by litt1e-p** [comment]
sorry, I run with wrong scheme

**Comment by ivanmoskalev** [comment]
Glad to know everything's alright for you! 👍

**Comment by litt1e-p** [comment]
thanks a lot
